-- 测量提醒 + 一次性订阅消息
-- ⚠️ Supabase SQL Editor 容易 timeout：请改用分步脚本
--   1) add_reminder_subscribe_step1_tokens.sql  （先跑）
--   2) add_reminder_subscribe_step2_users.sql   （逐条 Run）
--   3) add_reminder_subscribe_verify.sql        （检查）
-- 下方为完整版（表很大或 Editor 超时时不要一次 Run 全文件）

-- 1) 用户提醒偏好（存 wx_users）
ALTER TABLE wx_users
  ADD COLUMN IF NOT EXISTS reminder_enabled BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE wx_users
  ADD COLUMN IF NOT EXISTS reminder_time VARCHAR(5) NOT NULL DEFAULT '09:00';

ALTER TABLE wx_users
  ADD COLUMN IF NOT EXISTS reminder_timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai';

COMMENT ON COLUMN wx_users.reminder_enabled IS '是否开启测量提醒（一次性订阅消息）';
COMMENT ON COLUMN wx_users.reminder_time IS '每日提醒时刻 HH:mm（用户本地时区）';
COMMENT ON COLUMN wx_users.reminder_timezone IS '提醒时区，默认 Asia/Shanghai';

CREATE INDEX IF NOT EXISTS idx_wx_users_reminder_enabled
  ON wx_users (reminder_enabled)
  WHERE reminder_enabled = true;

-- 2) 一次性订阅额度（用户授权一次 = 可发一条）
CREATE TABLE IF NOT EXISTS subscribe_message_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  openid VARCHAR(128) NOT NULL,
  template_id VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL CHECK (status IN ('accept', 'reject', 'ban')),
  scheduled_for TIMESTAMPTZ NOT NULL,
  sent_at TIMESTAMPTZ,
  consumed BOOLEAN NOT NULL DEFAULT false,
  send_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subscribe_tokens_pending
  ON subscribe_message_tokens (scheduled_for, consumed, status)
  WHERE consumed = false AND status = 'accept';

CREATE INDEX IF NOT EXISTS idx_subscribe_tokens_openid
  ON subscribe_message_tokens (openid, created_at DESC);

-- 3) 订阅消息模板 ID（代码默认值，也可通过环境变量 WX_SUBSCRIBE_TEMPLATE_ID 覆盖）
-- n_7gRV7nCOVIiK2TBvOZOfFVxOGqxMqNm1_j1ntEiDU
