-- 测量提醒迁移 · 第 1 步（先跑这个，通常最快）
-- Supabase SQL Editor：每次只选中并运行「一个代码块」，不要一次 Run 全文件

-- A. 新表（与 wx_users 无关，一般秒过）
CREATE TABLE IF NOT EXISTS subscribe_message_tokens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  openid VARCHAR(128) NOT NULL,
  template_id VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL CHECK (status IN ('accept', 'reject', 'ban')),
  scheduled_for TIMESTAMPTZ NOT NULL,
  sent_at TIMESTAMPTZ,
  consumed BOOLEAN NOT NULL DEFAULT false,
  send_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_subscribe_tokens_pending
  ON subscribe_message_tokens (scheduled_for, consumed, status)
  WHERE consumed = false AND status = 'accept';

CREATE INDEX IF NOT EXISTS idx_subscribe_tokens_openid
  ON subscribe_message_tokens (openid, created_at DESC);
