-- =============================================================================
-- 【活动数据库】只需在 Supabase SQL Editor 中执行本文件这一份即可（不要执行别的 promo_*.sql）
-- =============================================================================
-- 可配置「连续记录领礼品」类活动（多期复用）
-- 1) promo_campaigns：每期一条（slug 唯一），配置统计窗口、所需连续天数；legacy 列 grand/second 与后台列表兼容
-- 2) promo_campaign_prize_tiers：任意数量奖项档位（sort_order 越小越优先，先到先得）
-- 3) promo_campaign_claims：按 campaign_slug + user_id 唯一，prize_tier 存 tier_key
--
-- 若库里曾存在旧表 public.promo_202604_consecutive_claims，文末 DO 块会自动把数据迁到本方案（可忽略若不存在）。
-- Next.js：GET/POST /api/promo/campaign（可选 ?slug= 覆盖环境变量）、PROMO_CAMPAIGN_SLUG、PROMO_ADMIN_KEY

CREATE TABLE IF NOT EXISTS public.promo_campaigns (
  slug text PRIMARY KEY,
  title text NOT NULL DEFAULT '',
  window_start_date date NOT NULL,
  window_end_date date NOT NULL,
  required_streak_days integer NOT NULL DEFAULT 30 CHECK (required_streak_days >= 1),
  grand_prize_slots integer NOT NULL DEFAULT 1 CHECK (grand_prize_slots >= 0),
  second_prize_slots integer NOT NULL DEFAULT 3 CHECK (second_prize_slots >= 0),
  grand_prize_label text NOT NULL DEFAULT '上臂式电子血压计 1 台',
  second_prize_label text NOT NULL DEFAULT '体脂秤/臂带/健康小礼品（随机）1 份',
  tz text NOT NULL DEFAULT 'Asia/Shanghai',
  is_enabled boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT promo_campaigns_window_ok CHECK (window_end_date >= window_start_date)
);

-- 已存在旧表结构时补齐奖品文案列（可在后台 /admin/promo 修改）
ALTER TABLE public.promo_campaigns
  ADD COLUMN IF NOT EXISTS grand_prize_label text NOT NULL DEFAULT '上臂式电子血压计 1 台';
ALTER TABLE public.promo_campaigns
  ADD COLUMN IF NOT EXISTS second_prize_label text NOT NULL DEFAULT '体脂秤/臂带/健康小礼品（随机）1 份';

COMMENT ON TABLE public.promo_campaigns IS '连续打卡类活动配置（后台可改期数与名额）';

CREATE TABLE IF NOT EXISTS public.promo_campaign_claims (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_slug text NOT NULL REFERENCES public.promo_campaigns (slug) ON DELETE RESTRICT,
  user_id text NOT NULL,
  prize_tier text NOT NULL,
  recipient_name text NOT NULL,
  phone text NOT NULL,
  address text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT promo_campaign_claims_user_per_campaign UNIQUE (campaign_slug, user_id)
);

CREATE INDEX IF NOT EXISTS idx_promo_campaign_claims_slug ON public.promo_campaign_claims (campaign_slug);
CREATE INDEX IF NOT EXISTS idx_promo_campaign_claims_created ON public.promo_campaign_claims (created_at);

-- -----------------------------------------------------------------------------
-- 多档位奖项（任意数量；sort_order 越小越优先，与先到先得一致）
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.promo_campaign_prize_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  campaign_slug text NOT NULL REFERENCES public.promo_campaigns (slug) ON DELETE CASCADE,
  tier_key text NOT NULL,
  tier_name text NOT NULL DEFAULT '',
  sort_order int NOT NULL,
  slots int NOT NULL DEFAULT 0 CHECK (slots >= 0),
  label text NOT NULL DEFAULT '',
  CONSTRAINT promo_campaign_prize_tiers_slug_key UNIQUE (campaign_slug, tier_key),
  CONSTRAINT promo_campaign_prize_tiers_slug_sort UNIQUE (campaign_slug, sort_order),
  CONSTRAINT promo_campaign_prize_tiers_key_fmt CHECK (
    tier_key ~ '^[a-z][a-z0-9_]*$' AND char_length(tier_key) <= 32
  )
);

CREATE INDEX IF NOT EXISTS idx_promo_campaign_prize_tiers_slug ON public.promo_campaign_prize_tiers (campaign_slug);

COMMENT ON TABLE public.promo_campaign_prize_tiers IS '活动奖项档位；claim.prize_tier 存 tier_key';

-- 放宽领取行的 prize_tier，与 tier_key 格式一致
ALTER TABLE public.promo_campaign_claims DROP CONSTRAINT IF EXISTS promo_campaign_claims_prize_tier_check;
ALTER TABLE public.promo_campaign_claims ADD CONSTRAINT promo_campaign_claims_prize_tier_fmt CHECK (
  char_length(prize_tier) >= 1
  AND char_length(prize_tier) <= 32
  AND prize_tier ~ '^[a-z][a-z0-9_]*$'
);

-- 默认一期（与原 202604 活动一致；可按需在后台改日期或新建 slug）
INSERT INTO public.promo_campaigns (
  slug, title, window_start_date, window_end_date,
  required_streak_days, grand_prize_slots, second_prize_slots,
  grand_prize_label, second_prize_label, tz, is_enabled
)
VALUES (
  'consecutive-streak',
  '连续记录领血压计',
  DATE '2026-04-15',
  DATE '2026-05-31',
  30,
  1,
  3,
  '上臂式电子血压计 1 台',
  '体脂秤/臂带/健康小礼品（随机）1 份',
  'Asia/Shanghai',
  true
)
ON CONFLICT (slug) DO NOTHING;

-- 各活动默认从 promo_campaigns 同步两档（已存在同 key 则跳过）
INSERT INTO public.promo_campaign_prize_tiers (campaign_slug, tier_key, tier_name, sort_order, slots, label)
SELECT c.slug, 'grand', '大奖', 1, c.grand_prize_slots, c.grand_prize_label
FROM public.promo_campaigns c
ON CONFLICT (campaign_slug, tier_key) DO NOTHING;

INSERT INTO public.promo_campaign_prize_tiers (campaign_slug, tier_key, tier_name, sort_order, slots, label)
SELECT c.slug, 'second', '二等奖', 2, c.second_prize_slots, c.second_prize_label
FROM public.promo_campaigns c
ON CONFLICT (campaign_slug, tier_key) DO NOTHING;

-- 按活动配置计算：仅统计 window_start_date～window_end_date（含端点）内、按活动 tz 换算的日历日；
-- 连续「有记录」的日历日以 created_at（入库时间）为准，避免手动补录把 recorded_at 填成任意测量日刷连续；
-- 无 created_at 的旧数据回退到 recorded_at。直接扫 bp_records，不受客户端分页影响。
CREATE OR REPLACE FUNCTION public.promo_campaign_max_streak(p_user_id text, p_slug text)
RETURNS integer
LANGUAGE plpgsql
STABLE
AS $func$
DECLARE
  ws date;
  we date;
  tzv text;
  d date;
  prev date;
  cur int := 0;
  best int := 0;
BEGIN
  SELECT c.window_start_date, c.window_end_date, c.tz
  INTO ws, we, tzv
  FROM public.promo_campaigns c
  WHERE c.slug = p_slug AND c.is_enabled;

  IF ws IS NULL THEN
    RETURN 0;
  END IF;

  FOR d IN
    SELECT DISTINCT (timezone(tzv::text, COALESCE(r.created_at, r.recorded_at)))::date AS day
    FROM public.bp_records r
    WHERE r.user_id = p_user_id
      AND (timezone(tzv::text, COALESCE(r.created_at, r.recorded_at)))::date >= ws
      AND (timezone(tzv::text, COALESCE(r.created_at, r.recorded_at)))::date <= we
    ORDER BY 1
  LOOP
    IF prev IS NULL THEN
      cur := 1;
    ELSIF d = prev + 1 THEN
      cur := cur + 1;
    ELSE
      cur := 1;
    END IF;
    IF cur > best THEN
      best := cur;
    END IF;
    prev := d;
  END LOOP;
  RETURN best;
END;
$func$;

CREATE OR REPLACE FUNCTION public.promo_campaign_streak_status(p_user_id text, p_slug text)
RETURNS jsonb
LANGUAGE plpgsql
AS $func$
DECLARE
  camp public.promo_campaigns%ROWTYPE;
  v_today date;
  v_phase text;
  v_streak int;
  v_claim jsonb;
  v_grand_left int;
  v_second_left int;
  v_prize_tiers jsonb;
  v_grand_slots int;
  v_second_slots int;
  req int;
BEGIN
  SELECT * INTO camp FROM public.promo_campaigns WHERE slug = p_slug LIMIT 1;

  IF NOT FOUND OR NOT camp.is_enabled THEN
    RETURN jsonb_build_object(
      'ok', false,
      'error', 'campaign_not_found',
      'campaign_slug', p_slug
    );
  END IF;

  v_today := (timezone(camp.tz::text, now()))::date;

  IF v_today < camp.window_start_date THEN
    v_phase := 'not_started';
  ELSIF v_today > camp.window_end_date THEN
    v_phase := 'ended';
  ELSE
    v_phase := 'active';
  END IF;

  req := camp.required_streak_days;
  v_streak := public.promo_campaign_max_streak(p_user_id, p_slug);

  SELECT jsonb_build_object(
    'prize_tier', c.prize_tier,
    'tier_name', COALESCE(pt.tier_name, c.prize_tier),
    'recipient_name', c.recipient_name,
    'phone', c.phone,
    'address', c.address,
    'created_at', c.created_at
  )
  INTO v_claim
  FROM public.promo_campaign_claims c
  LEFT JOIN public.promo_campaign_prize_tiers pt
    ON pt.campaign_slug = c.campaign_slug AND pt.tier_key = c.prize_tier
  WHERE c.campaign_slug = p_slug AND c.user_id = p_user_id
  LIMIT 1;

  SELECT COALESCE(
    (
      SELECT jsonb_agg(
        jsonb_build_object(
          'tier_key', t.tier_key,
          'tier_name', t.tier_name,
          'sort_order', t.sort_order,
          'slots', t.slots,
          'label', t.label,
          'remaining', GREATEST(
            t.slots - COALESCE((
              SELECT COUNT(*)::int FROM public.promo_campaign_claims cc
              WHERE cc.campaign_slug = p_slug AND cc.prize_tier = t.tier_key
            ), 0),
            0
          )
        )
        ORDER BY t.sort_order
      )
      FROM public.promo_campaign_prize_tiers t
      WHERE t.campaign_slug = p_slug
    ),
    '[]'::jsonb
  ) INTO v_prize_tiers;

  v_grand_slots := COALESCE((
    SELECT slots FROM public.promo_campaign_prize_tiers
    WHERE campaign_slug = p_slug AND tier_key = 'grand' LIMIT 1
  ), camp.grand_prize_slots);
  v_second_slots := COALESCE((
    SELECT slots FROM public.promo_campaign_prize_tiers
    WHERE campaign_slug = p_slug AND tier_key = 'second' LIMIT 1
  ), camp.second_prize_slots);

  v_grand_left := v_grand_slots - COALESCE((
    SELECT COUNT(*)::int FROM public.promo_campaign_claims
    WHERE campaign_slug = p_slug AND prize_tier = 'grand'
  ), 0);
  v_second_left := v_second_slots - COALESCE((
    SELECT COUNT(*)::int FROM public.promo_campaign_claims
    WHERE campaign_slug = p_slug AND prize_tier = 'second'
  ), 0);

  RETURN jsonb_build_object(
    'ok', true,
    'campaign_slug', camp.slug,
    'title', camp.title,
    'activity_phase', v_phase,
    'window_start', camp.window_start_date::text,
    'window_end', camp.window_end_date::text,
    'timezone', camp.tz,
    'required_streak_days', req,
    'prize_tiers', v_prize_tiers,
    'grand_prize_slots', v_grand_slots,
    'second_prize_slots', v_second_slots,
    'grand_prize_label', camp.grand_prize_label,
    'second_prize_label', camp.second_prize_label,
    'streak_days_in_window', v_streak,
    'qualified', (v_streak >= req),
    'my_claim', v_claim,
    'remaining_grand', GREATEST(v_grand_left, 0),
    'remaining_second', GREATEST(v_second_left, 0),
    'sold_out', NOT EXISTS (
      SELECT 1 FROM public.promo_campaign_prize_tiers t
      WHERE t.campaign_slug = p_slug
        AND t.slots > COALESCE((
          SELECT COUNT(*)::int FROM public.promo_campaign_claims c
          WHERE c.campaign_slug = p_slug AND c.prize_tier = t.tier_key
        ), 0)
    )
  );
END;
$func$;

CREATE OR REPLACE FUNCTION public.promo_campaign_streak_claim(
  p_user_id text,
  p_slug text,
  p_recipient_name text,
  p_phone text,
  p_address text
)
RETURNS jsonb
LANGUAGE plpgsql
AS $func$
DECLARE
  camp public.promo_campaigns%ROWTYPE;
  v_today date;
  v_streak int;
  v_prize text;
  v_prize_label text;
  v_used bigint;
  r record;
  v_name text := trim(both from coalesce(p_recipient_name, ''));
  v_phone text := trim(both from regexp_replace(coalesce(p_phone, ''), '\s', '', 'g'));
  v_addr text := trim(both from coalesce(p_address, ''));
  req int;
  v_cap int;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(p_slug), 928471522);

  SELECT * INTO camp FROM public.promo_campaigns WHERE slug = p_slug LIMIT 1;
  IF NOT FOUND OR NOT camp.is_enabled THEN
    RETURN jsonb_build_object('ok', false, 'error', 'campaign_not_found');
  END IF;

  v_today := (timezone(camp.tz::text, now()))::date;

  IF v_today < camp.window_start_date THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_started');
  END IF;
  IF v_today > camp.window_end_date THEN
    RETURN jsonb_build_object('ok', false, 'error', 'ended');
  END IF;

  IF char_length(v_name) < 2 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_name');
  END IF;
  IF char_length(v_phone) < 8 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_phone');
  END IF;
  IF char_length(v_addr) < 6 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invalid_address');
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.promo_campaign_claims
    WHERE campaign_slug = p_slug AND user_id = p_user_id
  ) THEN
    RETURN jsonb_build_object('ok', false, 'error', 'already_claimed');
  END IF;

  req := camp.required_streak_days;
  v_streak := public.promo_campaign_max_streak(p_user_id, p_slug);
  IF v_streak < req THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_qualified');
  END IF;

  v_cap := COALESCE((
    SELECT SUM(slots)::int FROM public.promo_campaign_prize_tiers WHERE campaign_slug = p_slug
  ), 0);

  IF v_cap <= 0 THEN
    RETURN jsonb_build_object('ok', false, 'error', 'sold_out');
  END IF;

  FOR r IN
    SELECT tier_key, slots, label
    FROM public.promo_campaign_prize_tiers
    WHERE campaign_slug = p_slug
    ORDER BY sort_order ASC
  LOOP
    SELECT COUNT(*) INTO v_used
    FROM public.promo_campaign_claims
    WHERE campaign_slug = p_slug AND prize_tier = r.tier_key;

    IF v_used < r.slots THEN
      v_prize := r.tier_key;
      v_prize_label := r.label;
      EXIT;
    END IF;
  END LOOP;

  IF v_prize IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'sold_out');
  END IF;

  INSERT INTO public.promo_campaign_claims (campaign_slug, user_id, prize_tier, recipient_name, phone, address)
  VALUES (p_slug, p_user_id, v_prize, v_name, v_phone, v_addr);

  RETURN jsonb_build_object(
    'ok', true,
    'prize_tier', v_prize,
    'prize_label', v_prize_label,
    'campaign_slug', p_slug,
    'slots_total', v_cap
  );
EXCEPTION
  WHEN unique_violation THEN
    RETURN jsonb_build_object('ok', false, 'error', 'already_claimed');
END;
$func$;

GRANT EXECUTE ON FUNCTION public.promo_campaign_max_streak(text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.promo_campaign_streak_status(text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.promo_campaign_streak_claim(text, text, text, text, text) TO service_role;

-- 可选：从旧表迁入（仅当旧表仍存在时）
DO $migrate$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'promo_202604_consecutive_claims'
  ) THEN
    INSERT INTO public.promo_campaign_claims (
      campaign_slug, user_id, prize_tier, recipient_name, phone, address, created_at
    )
    SELECT
      'consecutive-streak',
      o.user_id,
      o.prize_tier,
      o.recipient_name,
      o.phone,
      o.address,
      o.created_at
    FROM public.promo_202604_consecutive_claims o
    ON CONFLICT (campaign_slug, user_id) DO NOTHING;
  END IF;
END;
$migrate$;
